### ISSUE TITLE
Have you considered using coloration to generate vim themes?

### ISSUE THREAD

**Issue by metalelf0** [mswift42/themecreator#1]
Hi, nice project! Have you considered the [coloration](https://github.com/sickill/coloration) ruby gem?  It allows converting textmate themes to vim themes. I see you don't have a ruby runtime right now (on github pages, I mean), but this could be an interesting solution to batch-add vim themes for preset themes, at least.

HTH :)

**Comment by mswift42** [comment]
Thanks, coloration looks nice, but I'll probably roll my own vim template, than it's easier to introduce changes to the syntax colouring for all templates.

**Comment by mswift42** [comment]
Vim support has now been added :)
