### ISSUE TITLE
Allow naming for Terminal Profile color profile settings

### ISSUE THREAD

**Issue by aphive** [mswift42/themecreator#16]
First off, great job putting this together. 

Is there a way to get a reference map added to the interface that shows which filed matches what option in the Terminal Profile settings if even in the documentation?

For example:  mainbg = pallet color 0

I tried to see if I could map things out but it just got even weirder...

Here is the example theme metalheart from your site:

FIELD | VALUE
-- | --
mainbg | `#1d272a`
mainfg | `#8693ae`
builtin | `#9a91b8`
keyword | `#6e94ad`
string | `#ba899c`
functionname | `#937aba`
variable | `#638f81`
type | `#7a9f81`
constant | `#5980a3`
comment | `#727272`
warning | `#ff0000`
warning2 | `#ff8800`

This is how it generated in the terminal profile:

IN TERMINAL          | METALHEART | ON THEME CREATOR
--                   | --         | --
palette color 0      | `#1D272A`  | mainbg
palette color 1      | `#7B87A0`  |  
palette color 2      | `#95A0B8`  |  
palette color 3      | `#717B92`  |  
palette color 4      | `#667084`  |  
palette color 5      | `#937ABA`  |  
palette color 6      | `#7A9F81`  |  
palette color 7      | `#6E94AD`  | keyword
palette color 8      | `#5980A3`  | constant
palette color 9      | `#638F81`  | variable
palette color 10     | `#7A9F81`  | type
palette color 11     | `#FF0000`  | warning
palette color 12     | `#937ABA`  | functionname
palette color 13     | `#667084`  |  
palette color 14     | `#7B87A0`  |  
palette color 15     | `#8693AE`  | mainfg
Text                 | `#8693AE`  | mainfg
Background           | `#1D272A`  | mainbg
Cursor Foreground    | `#1D272A`  | mainbg
Cursor Background    | `#8693AE`  | mainfg
Highlight Foreground | `#2E3440`  |  
Highlight Background | `#88C0D0`  |

Notice that some of the colors in the theme generator did not even get used and some random colors were used instead.

**Comment by mswift42** [comment]
Hi, Thanks for this.

Did you take a look at the [template](https://github.com/mswift42/themecreator/blob/7c6a4ab8b2150acb6edd038448f1ae169f34c954/app.core/resources/public/templates/gnome-terminal.txt#L70) ?

The "random colors" are shades (darker or lighter) of mainfg and mainbg.

**Comment by aphive** [comment]
Sorry for the late reply, that makes sense. Thanks.
