### ISSUE TITLE
Make Ruby integers color as Constants rather than mainfg

### ISSUE THREAD

**Issue by sts10** [mswift42/themecreator#2]
A small, subtle thing, but I think it be nicer if you gave integers in Ruby a different color than `mainfg` to separate them from variables and methods more. I'd suggest using the color set as `constant`. 

Here's how it looks now-- lot of `mainfg` in there I'd say.
![screen shot 2016-01-16 at 11 53 59 am](https://cloud.githubusercontent.com/assets/4871664/12373482/86d9ba58-bc48-11e5-81b5-7f6a1f38c789.png)

**Comment by mswift42** [comment]
Done! added with commit [108d9fc](https://github.com/mswift42/themecreator/commit/108d9fcde72768bfb03d51627f955f0b172a6b50).
