### ISSUE TITLE
Issues WIth MELPA Submission

### ISSUE THREAD

**Issue by SamuelBanya** [mswift42/themecreator#26]
I am in pending status for the 'morrowind-emacs-theme' related theme I created with 'themecreator' on MELPA aka the Emacs based package site itself:
https://github.com/melpa/melpa/pull/8095

These are the issues that were generated as a result of the 'themecreator' itself, but I'm not sure how I can fix this because this is as a result of 'themecreator' itself:
```
8 issues found:
1:0: error: Package should have a Homepage or URL header.
1:0: warning: The word "emacs" is redundant in Emacs package names.
26:0: error: Package should have a non-empty ;;; Commentary section.
250:8: warning: Closing parens should not be wrapped onto new lines.
266:3: warning: Closing parens should not be wrapped onto new lines.
```

Including this here in case anyone like myself wants to use this tool to make themes for MELPA, and wants to get approved.

Please let me know if there is anything within the 'themecreator' code base that could be revised accordingly, thanks.

**Comment by mswift42** [comment]
Hi, thank you for opening this issue.

You can find the emacs template [in the templates folder here](https://github.com/mswift42/themecreator/tree/master/app.core/resources/public/templates).

Please feel free to clone this repo, adapt the emacs template to fit with the current melpa package codestyle and send 
a pull request.

**Comment by mswift42** [comment]
Closing this now because of a lack of response.

**Comment by SamuelBanya** [comment]
@mswift42 
Please check the merge request here:
https://github.com/mswift42/themecreator/pull/33
