### ISSUE TITLE
Program not showing up

### ISSUE THREAD

**Issue by Anvilo** [mswift42/themecreator#3]
Hi,

I have tried using your app for customizing emacs (26), I have moved your whole project folder to xampp and then navigated to "http://localhost/themecreator-master/app/resources/" with my browser. The upper frame loaded up along with the footer but nothing else showed up making the app unusable. Is this an issue or am I using your software wrong? It is hard to tell, because your installation instructions are barebones.

**Comment by mswift42** [comment]
Hi, 

There are no installation instruction, because installation is not necessary.
To use it go to http://mswift42.github.io/themecreator/.

If you want to run it locally, you need to use the gh-pages branch.
