### ISSUE TITLE
Doesn't appear to be compatible with terminal-only editors

### ISSUE THREAD

**Issue by ErikBoesen** [mswift42/themecreator#5]
I've tried to use a vim theme created with ThemeCreator in my terminal, but since only `guifg`/`guibg` properties are specified in themes output, the theme has no effect.

Color hex codes can be converted to xterm-256 colors pretty easily. I found [this Python package to do it](https://github.com/magarcia/python-x256).

Let me know if I can help with this.

**Comment by mswift42** [comment]
Which terminal are you using ?

**Comment by ErikBoesen** [comment]
iTerm2.

**Comment by ErikBoesen** [comment]
Do other terminals support GUI colors? I admittedly don't know.

**Comment by mswift42** [comment]
Do you have the line

> set termguicolors

set in your `.vimrc` ?

I

**Comment by mswift42** [comment]
Iterm2 also has true color support.

See here:

[True Colour support in Terminals](https://gist.github.com/XVilka/8346728)

**Comment by ErikBoesen** [comment]
Ah, adding that does fix it! Thank you!

Still, don't you think ThemeCreator should provide 256color codes by default? Again not my area of expertise.

**Comment by mswift42** [comment]
I don't think it's important anymore, because all mainstream (and most non mainstream) terminals now support true colours.

**Comment by ErikBoesen** [comment]
Okay, that's fair. Thanks for your help!

**Comment by mswift42** [comment]
No worries.

**Comment by ErikBoesen** [comment]
Sorry to revive this issue again; do you think it might be reasonable to automatically execute `set termguicolors` in generated themes?

**Comment by mswift42** [comment]
No, that would mean overriding a users config, and I don't want to do that.

I'll add an entry to the README though.

**Comment by ErikBoesen** [comment]
Makes sense!
