### ISSUE TITLE
Copyright year in Emacs theme is hard-coded to 2016

### ISSUE THREAD

**Issue by goodmami** [mswift42/themecreator#8]
The copyright year in the comment at the start of an Emacs theme is hard-coded to 2016:

https://github.com/mswift42/themecreator/blob/3480d24d948c3e390cd1692ef237fd49be25a9d3/app/resources/templates/emacs.txt#L3

It would be nicer if that was also a `{{copyrightyear}}` template variable that got filled in with the current year. Or, better yet, if the user could select the license itself (but this issue is just about the copyright year).

**Comment by mswift42** [comment]
This has been fixed with latest update.
