### ISSUE TITLE
Unable to download themes 

### ISSUE THREAD

**Issue by peregrinat0r** [mswift42/themecreator#9]
I've just discovered this tool and decided to try it out. Created a theme, saved it (although I can't find it anywhere), but on clicking the download button followed by any of the available formats, nothing happens. No download prompt or any such thing. I'm on a slightly patchy network if that means anything. Any help?

**Comment by mswift42** [comment]
Yes, sorry, I saw this weekend that download is broken.

Until it is fixed you can create and download themes if you run themecreator locally.

to run themecreator locally:

- clone or download [themecreator](https://github.com/mswift42/themecreator).
- [install](https://clojure.org/guides/getting_started) clojure and the clojure cli tools.
- go into the `app.core` directory and run `clj:A:fig:build`

**Comment by peregrinat0r** [comment]
Ahh cool. Will try this locally and check back later. Thank!

**Comment by mswift42** [comment]
download of themes at [themecreator](https://mswift42.github.io/themecreator/) is working again, so I'm closing this for now.
